version: '3'

services:
  negai-backend:
    build: .
    image: dias1618/aquila-backend-auth
    container_name: aquila-backend-auth
    ports:
        - 3002:3000
    restart: on-failure
    networks:
        - negai-backend_postgres-network

networks:
    negai-backend_postgres-network:
        external:
            name: negai-backend_postgres-network
